// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Note struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Title           sql.NullString
	Content         sql.NullString
	BackgroundColor sql.NullString
	CreateTime      time.Time
	UpdateTime      sql.NullTime
	DeleteTime      sql.NullTime
}

type User struct {
	ID         uuid.UUID
	Name       string
	Email      string
	Password   string
	CreateTime time.Time
	UpdateTime sql.NullTime
}
