# version: "3.7"

services:
  cockroach:
    image: cockroachdb/cockroach:v24.1.3@sha256:1936a3bf5a7121bca0ae78094f87073b96a513369661279698f6ef3985d4eb63
    container_name: cockroach
    volumes:
      - cockroach:/cockroach/cockroach-data
    ports:
      - 26257:26257
      - 8888:8080
    restart: always
    command: start-single-node --insecure
  pgweb:
    image: sosedoff/pgweb:0.15.0
    container_name: pgweb
    ports: 
      - "8085:8081" 
    links: 
      - cockroach:cockroach 
    environment:
      - DATABASE_URL=postgres://root:root@cockroach:26257/postgres?sslmode=disable
    depends_on:
      - cockroach
    restart: always
  redis:
    image: redis/redis-stack-server:7.4.0-v0@sha256:887cf87cc744e4588ccade336d0dbb943e4e46330f738653ccb3a7a55df2f186
    container_name: redis
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
  redisinsight:
    image: redis/redisinsight:2.54@sha256:938c50cf95f7389bc93ce4d26e6eed6855736a8e5b5b05f7e640f01d1be2d514
    container_name: redisinsight
    volumes:
      - redisinsight:/data
    ports:
      - 5540:5540
    depends_on:
      - redis
    restart: always
volumes:
  cockroach:
  redisinsight:
