// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/daniarmas/notes/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AccessTokenCacheDs is an autogenerated mock type for the AccessTokenCacheDs type
type AccessTokenCacheDs struct {
	mock.Mock
}

// CreateAccessToken provides a mock function with given fields: ctx, accessToken
func (_m *AccessTokenCacheDs) CreateAccessToken(ctx context.Context, accessToken *domain.AccessToken) error {
	ret := _m.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccessToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.AccessToken) error); ok {
		r0 = rf(ctx, accessToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAccessToken provides a mock function with given fields: ctx, id
func (_m *AccessTokenCacheDs) DeleteAccessToken(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccessToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAccessTokenById provides a mock function with given fields: ctx, id
func (_m *AccessTokenCacheDs) GetAccessTokenById(ctx context.Context, id uuid.UUID) (*domain.AccessToken, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAccessTokenById")
	}

	var r0 *domain.AccessToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.AccessToken, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.AccessToken); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AccessToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAccessTokenCacheDs creates a new instance of AccessTokenCacheDs. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccessTokenCacheDs(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccessTokenCacheDs {
	mock := &AccessTokenCacheDs{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
