// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AccessToken struct {
	ID             string  `json:"id"`
	UserID         string  `json:"userId"`
	RefreshTokenID string  `json:"refreshTokenId"`
	CreateTime     string  `json:"createTime"`
	UpdateTime     *string `json:"updateTime,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type RefreshToken struct {
	ID         string  `json:"id"`
	UserID     string  `json:"userId"`
	CreateTime string  `json:"createTime"`
	UpdateTime *string `json:"updateTime,omitempty"`
}

type Response struct {
	Code    int32           `json:"code"`
	Message string          `json:"message"`
	Details *string         `json:"details,omitempty"`
	Data    *SignInResponse `json:"data,omitempty"`
}

type SignInInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SignInResponse struct {
	User         *User  `json:"user"`
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type User struct {
	ID         string  `json:"id"`
	Name       string  `json:"name"`
	Email      string  `json:"email"`
	CreateTime string  `json:"createTime"`
	UpdateTime *string `json:"updateTime,omitempty"`
}
