// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AccessToken struct {
	ID             string  `json:"id"`
	UserID         string  `json:"userId"`
	RefreshTokenID string  `json:"refreshTokenId"`
	CreateTime     string  `json:"createTime"`
	UpdateTime     *string `json:"updateTime,omitempty"`
}

type File struct {
	ID            string  `json:"id"`
	NoteID        string  `json:"noteId"`
	OriginalFile  string  `json:"originalFile"`
	ProcessedFile *string `json:"processedFile,omitempty"`
	URL           string  `json:"url"`
	CreateTime    string  `json:"createTime"`
	UpdateTime    *string `json:"updateTime,omitempty"`
}

type Mutation struct {
}

type Note struct {
	ID         string  `json:"id"`
	UserID     string  `json:"userId"`
	Title      *string `json:"title,omitempty"`
	Content    *string `json:"content,omitempty"`
	Files      []*File `json:"files,omitempty"`
	CreateTime string  `json:"createTime"`
	UpdateTime *string `json:"updateTime,omitempty"`
}

type NotesInput struct {
	Cursor string `json:"cursor"`
}

type NotesResponse struct {
	Notes  []*Note `json:"notes,omitempty"`
	Cursor string  `json:"cursor"`
}

type Query struct {
}

type RefreshToken struct {
	ID         string  `json:"id"`
	UserID     string  `json:"userId"`
	CreateTime string  `json:"createTime"`
	UpdateTime *string `json:"updateTime,omitempty"`
}

type SignInInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SignInResponse struct {
	User         *User  `json:"user"`
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type User struct {
	ID         string  `json:"id"`
	Name       string  `json:"name"`
	Email      string  `json:"email"`
	CreateTime string  `json:"createTime"`
	UpdateTime *string `json:"updateTime,omitempty"`
}
